workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS release
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - tu_email@gmail.com
