name: detector_placas
description: "Aplicación de detección de placas vehiculares usando Flutter y Flask."

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2 # Solo para Android/iOS
  sqflite: ^2.2.3 # Solo para Android/iOS
  path_provider: ^2.0.14
  file_selector: ^1.0.3
  permission_handler: ^11.3.1
  google_ml_kit: ^0.19.0 
  http: ^1.3.0
  image_picker: ^1.1.2
  provider: ^6.0.5
  image_picker_web: ^4.0.0 # Para capturar imágenes en Flutter Web
  sqflite_common_ffi: ^2.3.0 # Base de datos en Windows
  webview_flutter: ^4.2.2
  excel: ^4.0.6
  csv: ^6.0.0
  video_player: ^2.7.2  # Última versión recomendada
  shared_preferences: ^2.5.2  # Compatible con proyectos sin null safety
  google_mlkit_text_recognition: 0.14.0
  file_picker: ^9.0.0
  image: ^3.0.2
  ffi: ^2.1.4
  ffigen: ^7.2.6
  tflite_flutter: ^0.11.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/yolov5su_float32.tflite
    - assets/models/plate_detector.tflite
