# Uncomment this line to define a global platform for your project
platform :ios, '15.5'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Flutter Podfile setup
require_relative '../flutter_module/.ios/flutter_dependencies'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Añadir dependencias específicas si es necesario
  pod 'GoogleMLKit/BarcodeScanning', '3.2.0'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
